### ISSUE TITLE
Error upgrading reactui 

### ISSUE THREAD

**Issue by adriahuertas** [sibvisions/reactUI.example#4]
I get the following error when I upgrade the reactui dependency from version 1.0.41 to 1.0.43 in my "reactui.example" 

![error](https://user-images.githubusercontent.com/91001941/201932669-8a1e1132-feab-4ce5-a651-ce40dd840888.png)

**Comment by rjahn** [comment]
We introduced [reactUIDesigner](https://github.com/sibvisions/reactUIDesigner). I guess it's missing.

**Comment by maximilianweidenauer** [comment]
Just remove the property `designerViewCallback` from the ProfileMenu component then its gone.

**Comment by rjahn** [comment]
see here [CustomAppWrapper](https://github.com/sibvisions/reactUI.example/blob/main/src/features/CustomAppWrapper.tsx)

**Comment by rjahn** [comment]
Use latest source from repository

**Comment by maximilianweidenauer** [comment]
The button to enable the designer used to be in the ProfileMenu, now that it is changed, I've removed the possibility to add this property to the ProfileMenu.

**Comment by adriahuertas** [comment]
> Just remove the property `designerViewCallback` from the ProfileMenu component then its gone.

That works at first but it triggers a missing property error later on. Anyway, I'll get the latest source from repository as @rjahn suggested.
