### ISSUE TITLE
Is there a way to notice data changes from a replaced screen?

### ISSUE THREAD

**Issue by adriahuertas** [sibvisions/reactUI.example#6]
So, let's say I replace a screen and use dataProvider to get the data, which is, for instance, an array with values [1,2,3]. Now, I go to VisionX and change the row with value 2 from the array to 4. New values are [1,4,3]. My questions are:

1. Is there a way to update my old vector [1, 2, 3] to my new vector [1, 4, 3] if I've already replaced the screen without reloading the screen? The only thing I can think of is to reload dataProviders constantly, for example once a second, but that doesn't seem a good way. So, is there some kind of event to do that?
2. Let's say that, in my replaced screen, I create an input to modify the first value of the array. I insert 5, so now my array is [5, 2, 3]. How can I write this change to VisionX? Do I have to connect to visionX SQL server and write this new value by hand or is there a better option?

Thanks,

**Comment by rjahn** [comment]
Sry, but it's not clear what you mean with Vector and array.

With VisionX, you create GUIs for databases. You have e.g. a table which makes it possible to manage your database records. So if you change data, data is persisted in your DB.

If you have a different concurrent users for the same application, there's no sync mechanism. What should happen if different users are changing the same record. You can't reload. There's a locking mechanism in JVx framework, but it's not used in VisionX.

So it's possible to work with push events, but this project here is only the react client.

VisionX doesn't use SQL server. A postgreSQL db is embedded. VisionX is just a low-code tool and not the technology. It acts as runtime environment while developing, but in production use, your app is standalone deployed on a java application server like Tomcat or Wildfly. 

If you want to update records from your react UI, check other examples, e.g. https://github.com/sibvisions/reactUI.example/tree/main/src/readme-files/example-screen

**Comment by rjahn** [comment]
Please describe your use-case.

**Comment by adriahuertas** [comment]
Ok, I have a table like this in VX:
![imagen](https://user-images.githubusercontent.com/91001941/204280427-c8f83e1a-5a05-49d3-9a4c-f83c0ec42a42.png)
I replace this screen with reactui and it looks like this:
![imagen](https://user-images.githubusercontent.com/91001941/204280575-20517537-79a1-46db-b0f9-c1d4479a995d.png)
The color of the state depends on a value of some row that I've previously got with UseDataProviderData. Let's say something changes that value. Now, according to the new value, state should be red like this:
![imagen](https://user-images.githubusercontent.com/91001941/204281314-e1a17343-bb9f-4a1e-9243-14f5345c0196.png)
But to get that change of color I need to reload the browser because I use the UseDataProviderData just once at the beginning to replace the screen, so my "state" can't detect the new value unless I reload the browser. 
Is it possible to update the color without reloading the browser?

**Comment by rjahn** [comment]
So, you want a notification about data changes!

It's possible to reload a data provider without reloading the browser, but the server doesn't send a notification if you change a record.

First, you could add a button in your screen with a reload action. If you press this button, the data provider should change its records.

If you use VisionX, it's like a separate browser window - a different session - a different user. So, if user A is changing a record, all other users should get the update?

**Comment by adriahuertas** [comment]
Yes, all other user should get the update. Basically, I want to do this https://github.com/sibvisions/reactUI.example/tree/main/src/readme-files/replace-screen but with data that can change at any moment and therefore I have to update the screen.

Anyway, if I can't get a notification from the server I guess my best options are either an update button or a timer.

By the way, if I put an input here:

![imagen](https://user-images.githubusercontent.com/91001941/204288671-341ca80d-71bc-4e0b-aa88-b9625f64855a.png)
in order to modify some value I got from UseDataProviderData, I guess it is not possible to modify the original value (the one I've got from VX with UseDataProviderData), right?
Thanks,

**Comment by rjahn** [comment]
Please open a new Issue for the chart input.

**Comment by rjahn** [comment]
If you want a notification for "all other UIs", it's possible with Java code.
VisionX is a low-code platform and not all features of all libraries are available via VisionX UI.

But it's not a problem to implement a push mechanism or to use an existing mechanism of underlying JVx framework.

It's possible to send a notification to the UIs, e.g.

Add a button in your VisionX application for test purposes. Add an action event for this button and use following code:

``` java
public void doButtonbutton(UIActionEvent pEvent) throws Throwable
{
    save();
	
    getConnection().callAction("doPublish");
}
```

Now create the `doPublish` method in your server-side class:

``` java
public void doPublish()
{
    ICallBackBroker broker = SessionContext.getCurrentCallBackBroker();
	
    Thread th = new Thread(new Runnable()
    {
        public void run()
        {
            broker.publish("RELOAD", null, PublishMode.AllOtherMasterSessions);						
        }
    });
    th.start();
}
```

Now we need the `RELOAD` event handling. Simply create your own application class:

``` java
public class MyCustomApplication extends ProjX 
{
    public MyCustomApplication(UILauncher pLauncher) throws Throwable 
    {
        super(pLauncher);
    }

    @Override
    public void callBackResult(CallBackResultEvent pEvent)
    {
        if ("RELOAD".equals(pEvent.getInstruction()))
        {
            try
            {
                reload();
            }
            catch (Throwable th)
            {
                th.printStackTrace();
            }
        }
    }
}
```

To use the application, simply change mobile.xml or/and web.xml. Search for ProjX and replace the string with your classname (full qualified).

The button is only a demo. It's also possible to use an event after values changed....

For tests: If you press the Push button in VisionX, nothing will happen because VisionX runs in its own process and the reactUI runs in a separate process. Simply open the browser window multiple times for tests.

If you run your application in a load balanced environment, the built-in push mechanism won't work... But this is not a problem of used technologies, it's a general problem.
