### ISSUE TITLE
Save a changed value in a replaced screen

### ISSUE THREAD

**Issue by adriahuertas** [sibvisions/reactUI.example#8]
In this example:
![imagen](https://user-images.githubusercontent.com/91001941/204987052-f38686d4-8834-41b9-b3e7-422a68c7c51c.png)

We use the original data to replace the screen and paint the chart. If we add an input in the replaced screen to change some value, is it possible to save that changed? (To see that changed value reflected in the VX project, as if we had replaced that value directly in some table of VX)

**Comment by rjahn** [comment]
Did you read the API documentation: https://github.com/sibvisions/reactUI#api

Here's an example:
https://github.com/sibvisions/reactUI.example/tree/main/src/readme-files/example-screen

**Comment by adriahuertas** [comment]
Ok, so in that example a screen-wrapper is being used. I understand that I can also do that in a replaced screen by using the useRowSelect hook.

Thanks.
