### ISSUE TITLE
Create new project

### ISSUE THREAD

**Issue by adriahuertas** [sibvisions/reactUI.example#9]
I'm trying to create a new project following the readme steps but I'm getting an error.

What I do:

- npx create-react-app proj --template typescript
- Remove node_modules directory.
- Change react and react-dom version to 17.0.2 in package.json.
- npm install
- npm install @sibvisions/reactui
- add init-win script and run it
- Convert imports and App.tsx code to react 17
- npm start
- I get a blank page and the error "React.createElement: type is invalid -- expected a string or a class..."

**Comment by adriahuertas** [comment]
This is the error:
![imagen](https://github.com/sibvisions/reactUI.example/assets/91001941/4a902936-1d5d-4d45-853a-2b06c90b6128)

**Comment by adriahuertas** [comment]
Additional info: I have an old working project that uses the version 1.0.54 of reactUI. If I update the reactUI to the latest version, I get the same error. 

On the other hand, I have to use the URL in the readme of reactUI repository to access the old project project (as always) rather than the URL from the reactUI.example repository readme which, for some reason, aren't the same:
- ReactUI repo: http://localhost:3000/?language=de&appName=vxdemo&baseUrl=http%3A%2F%2Flocalhost%3A80%2Fservices%2Fmobile/#
- ReactUI.Example repo: http://localhost:3000/?language=en&appName=demo&baseUrl=http://localhost:8080/JVx.mobile/services/mobile#

**Comment by rjahn** [comment]
Thanks for reporting, we'll check this.

**Comment by maximilianweidenauer** [comment]
The first issue with the blank page should be resolved with version 2.2.4 which is now live.

For the second issue with the url... are you using visionx or the jvx.mobile server? If you are using visionx the url of the reactui repo is correct but with the server you need the example url

**Comment by adriahuertas** [comment]
You are right, I'm using visionx so I'll use the first link.

I've updated reactui to the last version and:
- My old project is working fine now (although I get an error when I try to modify the styles and visionX and save it. it says it can't find the project files or something like that even though I've already run the init-win script, but that also happened before, so who knows)
- When I create a new react project following the steps I've commented (basically creating react project, downgrading react to 17 and rendering the reactUI component in the app.tsx) and try to open the visionx project still doesn't work. I get the following error:
![imagen](https://github.com/sibvisions/reactUI.example/assets/91001941/899796b7-ef8d-462d-90fe-edde62d75935)

Should I do something else to create a new project with reactUI for visionX?

**Comment by maximilianweidenauer** [comment]
Could you maybe show me a screenshot from the network tab and the "startup" request, the click on payload, so I can check the issue?
Like this:
![image](https://github.com/sibvisions/reactUI.example/assets/66732863/b655cf42-b538-4363-9606-24b433642632)

**Comment by maximilianweidenauer** [comment]
It also seems like the css files aren't there, do you have a "color-scheme" and "theme" directory in your "public" directory of the project?

**Comment by rjahn** [comment]
We don't support Visionx in this project! It's something completely different.
